### PR TITLE
Optimized splitting chunks

### PR DESCRIPTION
**Pull request by KashShinfu**
Changed some code that takes up more memory or consumes more time (split chunks)

Optimized some unnecessary writing (rounder)

Forgive me for not using github's pull request

### CODE REVIEW

**Comment by Happy2018new** [comment]
Sorry for that I don't have too much time these days. I promise I will review this **PR** as soon as possible.
Thanks for waiting me.

**Comment by KashShinfu** [comment]
In addition, it should be noted that the operations of expanding the size and filling with air in this submission have not been changed yet. The support for my ".schem" format file has been completed by 90%. Meanwhile, the operation of filling with air has been removed, and the original building is directly disassembled. Since I really don't have a good understanding of Git, the new disassembling algorithm will be added in the next submission. Therefore, there is no need to point out the problems related to this operation in the current Pull Request.

**Comment by Happy2018new** [comment]
Could I trust you directly? Because I don't want to your logic like array out of index problems.

**Comment by KashShinfu** [comment]
I've tested it many times and never had any problems

**Comment by Happy2018new** [comment]
It still have some problems, but not related to out of index.

**Comment by Happy2018new** [comment]
I think I need some pictures to show you what the problem is.

**Comment by KashShinfu** [comment]
fine，I've been there

**Comment by Happy2018new** [comment]
image

**Comment by Happy2018new** [comment]
See this images, that shows how you arrange the import orders of each chunks.
The order is chunks in orange lines, and then chunks in green lines, and then chunks in red lines, and at last, the chunks in black lines.

**Comment by KashShinfu** [comment]
Do you mean that this will cause chunk loading problems and thus prevent a complete import?

**Comment by Happy2018new** [comment]
Or we could say that our robot went to the purple point on the graph.

image

**Comment by Happy2018new** [comment]
The robot goes to each purple dot in this way.
> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T

image

**Comment by Happy2018new** [comment]
You can see, for `A -> B -> C -> D -> E`, `F -> G -> H -> I -> J` and `P -> Q -> R -> S -> T`, everything is OK due to each time it moves to the next point, the robot moves up to 16 blocks and this is acceptable.

**Comment by Happy2018new** [comment]
But for `E -> F`, `J -> K` and `O -> P`, the robot will move for about `263.87` blocks, and it is too long. For example, if the robot move from **E** to **F**, and maybe the chunks in **E** is active but in **F** is not active. And it will cause that when the robot arrive area **F**, due to chunks in **F** is not loaded, so some blocks will failed to place.

**Comment by Happy2018new** [comment]
You have to solve this problem, or some blocks will lost due to the target chunks is not loaded.

**Comment by Happy2018new** [comment]
See this picture, you can make the robot move in the following order to solve the problem.
> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T

image

**Comment by KashShinfu** [comment]
It's easy to think, this may only take me half an hour, please wait for my good news

**Comment by Happy2018new** [comment]
Of course, please add comments in Chinese to your codes.

For example:
```go
/*
将 arr 中的 3 个整数修正到大于等于各自整数的值，
且该值是距离原整数的最近的 16 的整数倍。

即，对于 arr 中的一个整数 p，
找到一个最小的 num 使得
num >= p 且 num 可被 16 整除。

例如，如果 arr 是 [3]int{27, 12, 37}，
由于距离 27 最近的大于等于 27 的 16 的整数倍是 32，
而距离 12 最近的大于等于 12 的 16 的整数倍是 16，
且距离 37 最近的大于等于 37 的 16 的整数倍是 48，
故返回 [3]int{32, 16, 48}
func roundUpToNearestMultipleOf16(arr [3]int) [3]int {
	var result [3]int
	for index, num := range arr {
		remainder := num % 16
		if remainder == 0 {
			result[index] = num
		} else {
			result[index] = num + 16 - remainder
		}
	}
	return result
}
```

**Comment by KashShinfu** [comment]
I have completed the modification.

**Comment by KashShinfu** [comment]
If you don't have much time, just take a look at this effect video

**Comment by KashShinfu** [comment]
https://github.com/user-attachments/assets/66fa0457-94f1-427a-85fd-dc126ac8674b

If you don't have much time, just take a look at this effect video

**Comment by Happy2018new** [comment]
It sounds like everything is work as expected, I will review the codes as soon as possible.

**Comment by KashShinfu** [comment]
This commit removes the expansion operation on the building, so the original building will be directly split.

**Comment by Happy2018new** [comment]
> What needs to be changed?

你需要为以上列出的部分补充注释，并且按上面给出的建议改善目前已有的注释。

**Comment by KashShinfu** [comment]
我认为这些注释已经足够了
对于你的要求，我将我所定义的每个函数甚至是结构体都附上了确切的注释
但是对于SplitChunks函数，请原谅我无法按照你的建议在函数头进行注释，因为它本身就十分抽象
但是我为其中所有我自认为重要且更为抽象的代码行进行了更为详细的解释，确保连Go新手也能理解
我希望这能符合你的要求，谢谢

**Comment by Happy2018new** [comment]
我将会尽快完成审核并合并此拉取请求。

**Comment by KashShinfu** [comment]
辛苦了

**Review by Happy2018new — COMMENTED** [review]
看起来这些东西没能正常显示出来，现在让它显示一下（这是很久之前给出的建议了）

**Comment by Happy2018new** [comment]
Thanks for your contribution. Although I have not review this down, I decide to merge this as soon as possible!

**Pull request merged**
